<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $data = array (
  0 => 
  array (
    'id' => 1,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Institución',
    'icono' => 'fa fa-id-badge',
    'url' => 'admin.institucion.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '2',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  1 => 
  array (
    'id' => 2,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Sedes',
    'icono' => 'fa fa-building',
    'url' => 'admin.sede.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '3',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  2 => 
  array (
    'id' => 3,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Docentes',
    'icono' => 'fa fa-chalkboard-teacher',
    'url' => 'admin.docente.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '4',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  3 => 
  array (
    'id' => 4,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Cursos',
    'icono' => 'fa fa-book',
    'url' => 'admin.curso.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '5',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  4 => 
  array (
    'id' => 5,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Hilos',
    'icono' => 'fa fa-stream',
    'url' => 'admin.hilo.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '6',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  5 => 
  array (
    'id' => 6,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Asignaturas',
    'icono' => 'fa fa-book-open',
    'url' => 'admin.asignatura.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '7',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  6 => 
  array (
    'id' => 7,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Grados Académicos',
    'icono' => 'fa fa-graduation-cap',
    'url' => 'admin.gradoacademico.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '8',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  7 => 
  array (
    'id' => 8,
    'nombre' => 'Acudientes',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-user-friends',
    'url' => 'admin.acudiente.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '9',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  8 => 
  array (
    'id' => 9,
    'nombre' => 'Estudiantes',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-user-graduate',
    'url' => 'admin.estudiante.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '10',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  9 => 
  array (
    'id' => 10,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Año Escolar',
    'icono' => 'fa fa-calendar-alt',
    'url' => 'admin.anhoescolar.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '11',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  10 => 
  array (
    'id' => 11,
    'nombre' => 'Institución',
    'nombre_submenu' => 'Periodos Académicos',
    'icono' => 'fa fa-calendar-check',
    'url' => 'admin.periodoacademico.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '12',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  11 => 
  array (
    'id' => 12,
    'nombre' => 'Usuarios',
    'nombre_submenu' => 'Crear',
    'icono' => 'fa fa-user-plus',
    'url' => 'admin.usuarios.create',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '14',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-28 03:41:17',
  ),
  12 => 
  array (
    'id' => 14,
    'nombre' => 'Matriculados',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-user-check',
    'url' => 'admin.matriculado.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '15',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  13 => 
  array (
    'id' => 15,
    'nombre' => 'Notas',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-clipboard-list',
    'url' => 'admin.notas.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '16',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  14 => 
  array (
    'id' => 16,
    'nombre' => 'Notas Definitivas',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-file-contract',
    'url' => 'admin.notas-definitivas.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '17',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  15 => 
  array (
    'id' => 17,
    'nombre' => 'Notas Periodos',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-clipboard-list',
    'url' => 'estudiante.notasPeriodo',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '3',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-28 03:54:41',
  ),
  16 => 
  array (
    'id' => 18,
    'nombre' => 'Solicitar Paz y Salvo',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-clipboard-list',
    'url' => 'estudiante.notasPeriodo',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '17',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  17 => 
  array (
    'id' => 19,
    'nombre' => 'Solicitar Certificado Académico',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-file',
    'url' => 'estudiante.notasPeriodo',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '17',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  18 => 
  array (
    'id' => 20,
    'nombre' => 'Horario académico',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-calendar',
    'url' => 'estudiante.notasPeriodo',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '17',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  19 => 
  array (
    'id' => 21,
    'nombre' => 'Certificados',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-file',
    'url' => 'admin.certificados.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '18',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  20 => 
  array (
    'id' => 22,
    'nombre' => 'Mis Asignaturas',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-book-reader',
    'url' => 'docente.dashboard',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 4,
    'orden' => '1',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  21 => 
  array (
    'id' => 23,
    'nombre' => 'Calificar Estudiantes',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-edit',
    'url' => 'docente.dashboard',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 4,
    'orden' => '20',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  22 => 
  array (
    'id' => 24,
    'nombre' => 'Paz y Salvo',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-file',
    'url' => 'admin.pazysalvo.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '19',
    'created_at' => '2026-02-14 02:31:48',
    'updated_at' => '2026-02-14 02:31:48',
  ),
  23 => 
  array (
    'id' => 25,
    'nombre' => 'Usuarios',
    'nombre_submenu' => 'Listar',
    'icono' => 'fa fa-users',
    'url' => 'admin.usuarios.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '13',
    'created_at' => '2026-02-28 03:41:17',
    'updated_at' => '2026-02-28 03:41:17',
  ),
  24 => 
  array (
    'id' => 26,
    'nombre' => 'Mi Dashboard',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-tachometer-alt',
    'url' => 'estudiante.dashboard',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '1',
    'created_at' => '2026-02-28 03:54:41',
    'updated_at' => '2026-02-28 03:54:41',
  ),
  25 => 
  array (
    'id' => 27,
    'nombre' => 'Historial Académico',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-history',
    'url' => 'estudiante.history',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 2,
    'orden' => '2',
    'created_at' => '2026-02-28 03:54:41',
    'updated_at' => '2026-02-28 03:54:41',
  ),
  26 => 
  array (
    'id' => 30,
    'nombre' => 'Grado Cero',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-child',
    'url' => NULL,
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '99',
    'created_at' => now(),
    'updated_at' => now(),
  ),
  27 => 
  array (
    'id' => 31,
    'nombre' => 'Grado Cero',
    'nombre_submenu' => 'Criterios Evaluación',
    'icono' => 'fa fa-edit',
    'url' => 'admin.grado-cero.criterios.index',
    'tipo' => 'dropdown',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '100',
    'created_at' => now(),
    'updated_at' => now(),
  ),
  28 => 
  array (
    'id' => 32,
    'nombre' => 'Promoción de Grado',
    'nombre_submenu' => NULL,
    'icono' => 'fa fa-graduation-cap',
    'url' => 'admin.promocion.index',
    'tipo' => 'sencillo',
    'estado' => 1,
    'rol_id' => 1,
    'orden' => '120',
    'created_at' => now(),
    'updated_at' => now(),
  ),
);

        foreach ($data as $row) {
            Menu::updateOrCreate(['id' => $row['id']], $row);
        }
    }
}
